### ISSUE TITLE
Update the reset subscriptions so that it reflects the dynamic button attribute change

### ISSUE THREAD

**Issue by hodchUX** [mendix/DropdownDivConverter#12]
I have updated the js so that the reset subscription updates the dynamic label. 

[DropdownDivConverter-master.zip](https://github.com/mendix/DropdownDivConverter/files/917648/DropdownDivConverter-master.zip)

**Comment by JelteMX** [comment]
I'd rather have a PR or the piece of code that you changed than a ZIP

**Comment by hodchUX** [comment]
Add to the update rendering

`// Reordering the interface: selecting the siblings and putting them in the dropdown menu
        _updateRendering: function (callback) {
            
            // update label on attribute change from subscription
            if (this.dynamicButtonTitleAttribute !== "" && this._contextObj !== null) {
                this._dynamicLabel = true;
                this._buttonLabel = this._contextObj.get(this.dynamicButtonTitleAttribute);
            }
            // find all the siblings
            var siblings = domQuery(this.domNode).siblings();
            // loop through siblings and move them inside the dropdownMenu
            dojoArray.forEach(siblings, lang.hitch(this, function(entry, i) {
                domConstruct.place(entry,this.dropdownMenu,"last");
            }));
            
            this._renderInterface(this.startOpen,callback);
        },`

Include in reset subs
`// Reset subscriptions.
        _resetSubscriptions: function () {
            var _objectHandle = null,
                _attrHandle = null;
            if (this._handles){
                this._handles.forEach(function (handle, i) {
                    mx.data.unsubscribe(handle);
                });
                this._handles = [];
            }
            if (this._contextObj) {
                _objectHandle = this.subscribe({
                    guid: this._contextObj.getGuid(),
                    callback: lang.hitch(this, function (guid) {
                        this._updateRendering();
                    })
                });
                _attrHandle = this.subscribe({
                    guid: this._contextObj.getGuid(),
                    attr: this.dynamicButtonTitleAttribute,
                    callback: lang.hitch(this, function (guid, attr, attrValue) {
                        this._updateRendering();
                    })
                });
                this._handles = [_objectHandle, _attrHandle];
            }
        }`

**Comment by WillemUXMendix** [comment]
no, I've updated it :-)
Well... i solved it as well anyways. New version is now in the appstore :-)
