### ISSUE TITLE
I'm having problem with the Dynamic Dropdown Converter

### ISSUE THREAD

**Issue by sirazmillath** [mendix/DropdownDivConverter#13]
Hello, I hope you could help regarding my below requirement. We were trying to create a dynamic dropdown menu but we having a issue on showing it in dropdown. I've attached the screenshot of the work and the output. Thanks in advance.

![dropdown_issue_02](https://cloud.githubusercontent.com/assets/25412357/26667311/8bdb92e4-46b5-11e7-9ac5-12b70c465af4.jpg)

![dropdown_issue](https://cloud.githubusercontent.com/assets/25412357/26667315/9586082e-46b5-11e7-8676-4f177acd0886.jpg)

**Comment by WillemUXMendix** [comment]
I would not recommend this kind of advanced usage of the dropdowndivconverter. I did create a new version that allows for the nesting of dropdowndivconverters, but your case is more advanced than that. I would suggest trying out the latest version, but as  - seeing your model - the problem probably lies with combining all the different Mendix widgets you've used outside of their normal scope (navigation list is used for simple navigation lists). So if the problem persist I'd recommend just building your own custom widget that does exactly what you want it to do.
