### ISSUE TITLE
Error in widget with refresh in client from a microflow

### ISSUE THREAD

**Issue by sjorsschultz** [mendix/DropdownDivConverter#24]
Hi,

We have the dropdowndivconverter widget placed on static Entity detail page, say Task_View. In the menu we have buttons with conditional visibility according to the EntityStatus (ie. to-do, doing, done).
Each button sets the 'next' status and does a refresh in client from the microflow.
At this moment after the refresh the user is presented with an message "An error has occurred that might have been caused by fast reload. Refresh the page to fix it." If you press cancel instead of refresh, the menu contains the buttons for the old status and the new status, and the buttons for the new status have a additional class 'disabled'.
In the console we see the error "Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node."

The widget is set to self-closing and has no context object, although we tried without self-closing and with context object as well. It is the last child in the container.

The current workaround is to close the page as action in the microflow and then open it again.

**Comment by JelteMX** [comment]
This is an issue with the Mendix client and is due to changes. It can be fixed by implementing the DropdownDivConverter correctly (add child elements to a container). See the [troubleshooting](https://github.com/mendix/DropdownDivConverter/blob/master/README.md#troubleshooting) section for an explanation. I am closing this issue.

**Comment by sjorsschultz** [comment]
The documentation on GitHub is different then the MxApp store documentation. The GitHub implementation steps solved the problem, thanks.

**Comment by JelteMX** [comment]
We'll make sure it will be the same in the App Store
