### ISSUE TITLE
Troubleshoot workaround Mendix v8.3

### ISSUE THREAD

**Issue by beerscheffers** [mendix/DropdownDivConverter#29]
Regarding this comment in the appstore 

> For people that have issues since MX 7.18, this is due to an implementation issue, not a bug in the widget. Please have a look at the following link:

https://github.com/mendix/DropdownDivConverter/blob/master/README.md#troubleshooting

When converted to Mendix v8.3 from v8.0 we encountered the above issue again although we already had the steps mentioned implemented and worked before.

a fix for this was adding a additional container to the suggested implementation structure so ours now looks like this.

- Container
  - Container
    - Container
      - Element for dropdown
      - Element for dropdown
      - etc
    - DropdownDivConverter

**Comment by JelteMX** [comment]
With any luck we're moving away from the DropdownDivConverter, as this is doing DOM-manipulation and that shouldn't be done when using React. We created a replacement that should be supported soon (currently resides on my own Github):

Can you test [Dropdown Container](https://appstore.home.mendix.com/link/app/111568/) for me? You can move your container inside the widget, it has the same options as this widget.

**Comment by beerscheffers** [comment]
Thanks @JelteMX tested the Dropdown Container and works like a charm! 
This has now been implemented in our mendix v8.3 application,
We removed the DropdownDivConverter widget.

**Comment by JelteMX** [comment]
Added a comment to the README, will keep this issue open for now. When we transfer the other widget to the Mendix org, I will close this issue. Thanks for testing :-)
