### ISSUE TITLE
DropDownDivConverter triggers on login

### ISSUE THREAD

**Issue by LSFinaps** [mendix/DropdownDivConverter#7]
We created a message box with the dropdown converter with a notification at the top of the message box to indicate the amount of unread messages. When opened, the DropDownDivConverter triggers a microflow that marks all unread messages as read.

 However the microflow also triggers on login, probaly due to the rendering of the widget, which causes the message notifications to disappear on login.

Is it possible to fix this, so the microflow only triggers when the div is opened?

**Comment by LSFinaps** [comment]
Found the issue: the mfOnOpen was not connected to the on click of the dropdown button, but was instead called every time setup events was called

**Comment by WillemUXMendix** [comment]
Good to hear you guys figured it out.
To be honest, I had no clue of what it was about. mfOnOpen was pretty new to me.

good luck with it.
